{% set name = "tinycss2" %}
{% set version = "1.0.0" %}
{% set file_ext = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_value = "562d2e2b7ff191c0a9587ad5114dbf47d015d02f7449aa0ac41e7a725fbd77fc" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.{{ file_ext }}'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ file_ext }}
  '{{ hash_type }}': '{{ hash_value }}'

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  noarch: python

requirements:
  host:
    - python
    - pip
    - setuptools
    - webencodings >=0.4
  run:
    - python
    - webencodings >=0.4

test:
  imports:
    - tinycss2

about:
  home: https://github.com/Kozea/tinycss2
  license: BSD
  license_family: BSD
  license_file: LICENSE
  summary: Low-level CSS parser for Python
  description: |
    tinycss2 is a rewrite of tinycss with a simpler API, based on the more recent
    CSS Syntax Level 3 Specification.
  doc_url: http://tinycss2.readthedocs.io
  dev_url: https://github.com/Kozea/tinycss2

extra:
  recipe-maintainers:
    - johanneskoester
