{% set version = "1.5.0" %}

package:
  name: tinycss2
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/t/tinycss2/tinycss2-{{ version }}.tar.gz
  sha256: 6a7be7a654f38a2a55b61d2d97b1f65a7eb40d1cb4057ac37145f675f16efdf9

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - flit-core >=3.2,<4
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - webencodings >=0.4

test:
  imports:
    - tinycss2
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/Kozea/tinycss2
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Low-level CSS parser for Python
  description: |
    tinycss2 is a rewrite of tinycss with a simpler API, based on the more recent
    CSS Syntax Level 3 Specification.
  doc_url: http://tinycss2.readthedocs.io
  dev_url: https://github.com/Kozea/tinycss2

extra:
  recipe-maintainers:
    - johanneskoester
    - mrandrewandrade
    - thewchan
