{% set version = "1.1.0" %}

package:
  name: tinycss2
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/t/tinycss2/tinycss2-{{ version }}.tar.gz
  sha256: fbdcac3044d60eb85fdb2aa840ece43cf7dbe798e373e6ee0be545d4d134e18a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.5
    - pip
    - pytest-runner
  run:
    - python >=3.5
    - webencodings >=0.4

test:
  imports:
    - tinycss2

about:
  home: https://github.com/Kozea/tinycss2
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Low-level CSS parser for Python
  description: |
    tinycss2 is a rewrite of tinycss with a simpler API, based on the more recent
    CSS Syntax Level 3 Specification.
  doc_url: http://tinycss2.readthedocs.io
  dev_url: https://github.com/Kozea/tinycss2

extra:
  recipe-maintainers:
    - johanneskoester
    - mrandrewandrade
    - thewchan
